name: Testing HERA

on:
  workflow_dispatch:

jobs:
  run-tests:
    name: Testing HERA
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: |
            Statistics_and_Machine_Learning_Toolbox
            Parallel_Computing_Toolbox

      - name: Run Tests
        uses: matlab-actions/run-command@v2
        with:
          command: run('tests/run_HERA_tests.m')

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: MATLAB Test Results
          path: tests/logs/testResults.xml
          reporter: java-junit

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-and-results
          path: |
            tests/logs/*.txt
            tests/logs/*.xml
