name: Paper Check
on:
  workflow_dispatch:
jobs:
  paper-check:
    runs-on: ubuntu-latest
    name: Paper Check
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Paper
        uses: open-journals/open-journals-pdf-generator-action@v1
        with:
          journal: joss
          paper-path: paper/paper.md
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: paper/paper.pdf
